[2024-03-17T09:38:53.463+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-03-17T04:38:45.475961+00:00 [queued]>
[2024-03-17T09:38:53.468+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-03-17T04:38:45.475961+00:00 [queued]>
[2024-03-17T09:38:53.468+0500] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-17T09:38:53.605+0500] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): download_launches> on 2024-03-17 04:38:45.475961+00:00
[2024-03-17T09:38:53.607+0500] {standard_task_runner.py:60} INFO - Started process 14320 to run task
[2024-03-17T09:38:53.609+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'download_rocket_launches', 'download_launches', 'manual__2024-03-17T04:38:45.475961+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/download_rocket_launches.py', '--cfg-path', '/tmp/tmp13o468sl']
[2024-03-17T09:38:53.610+0500] {standard_task_runner.py:88} INFO - Job 11: Subtask download_launches
[2024-03-17T09:38:53.746+0500] {task_command.py:423} INFO - Running <TaskInstance: download_rocket_launches.download_launches manual__2024-03-17T04:38:45.475961+00:00 [running]> on host muhammadsami-Latitude-E6540
[2024-03-17T09:38:53.973+0500] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='download_rocket_launches' AIRFLOW_CTX_TASK_ID='download_launches' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T04:38:45.475961+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-17T04:38:45.475961+00:00'
[2024-03-17T09:38:57.198+0500] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/.env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/.env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/.env/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/.env/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/GettingStarted/dags/download_rocket_launches.py", line 35, in _download_launches
    f.write(respone)
TypeError: write() argument must be str, not Response
[2024-03-17T09:38:57.204+0500] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=download_launches, execution_date=20240317T043845, start_date=20240317T043853, end_date=20240317T043857
[2024-03-17T09:38:57.342+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task download_launches (write() argument must be str, not Response; 14320)
[2024-03-17T09:38:57.355+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-17T09:38:57.384+0500] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
