[2024-03-17T09:33:28.959+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-03-17T04:33:23.604793+00:00 [queued]>
[2024-03-17T09:33:28.973+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-03-17T04:33:23.604793+00:00 [queued]>
[2024-03-17T09:33:28.973+0500] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-17T09:33:29.131+0500] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): download_launches> on 2024-03-17 04:33:23.604793+00:00
[2024-03-17T09:33:29.136+0500] {standard_task_runner.py:60} INFO - Started process 13135 to run task
[2024-03-17T09:33:29.144+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'download_rocket_launches', 'download_launches', 'manual__2024-03-17T04:33:23.604793+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/download_rocket_launches.py', '--cfg-path', '/tmp/tmpy0nh187g']
[2024-03-17T09:33:29.145+0500] {standard_task_runner.py:88} INFO - Job 9: Subtask download_launches
[2024-03-17T09:33:29.513+0500] {task_command.py:423} INFO - Running <TaskInstance: download_rocket_launches.download_launches manual__2024-03-17T04:33:23.604793+00:00 [running]> on host muhammadsami-Latitude-E6540
[2024-03-17T09:33:29.912+0500] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='download_rocket_launches' AIRFLOW_CTX_TASK_ID='download_launches' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T04:33:23.604793+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-17T04:33:23.604793+00:00'
[2024-03-17T09:33:32.476+0500] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/.env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/.env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/.env/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/.env/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/muhammadsami/Public/Projects/Airflow/DataPipelineswithApacheAirflow/GettingStarted/dags/download_rocket_launches.py", line 30, in _download_launches
    f.write(respone)
TypeError: write() argument must be str, not Response
[2024-03-17T09:33:32.483+0500] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=download_launches, execution_date=20240317T043323, start_date=20240317T043328, end_date=20240317T043332
[2024-03-17T09:33:32.737+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task download_launches (write() argument must be str, not Response; 13135)
[2024-03-17T09:33:32.767+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-17T09:33:32.789+0500] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
